Add constant type to overridden DateTime::COOKIE
Constant properties are allowed since PHP 8.3, which is the minimum version for the ICanBoogie/DateTime library already. With 8.4, I'm getting the following error when the constant type is not explicitly specified:

```
Fatal error: Type of ICanBoogie\DateTime::COOKIE must be compatible with DateTimeInterface::COOKIE of type string in /home/.../vendor/icanboogie/datetime/lib/DateTime.php on line 169
```